language: java

jdk:
  - openjdk8

sudo: required

os:
  - linux

branches:
  except:
    - /^feature-.*$/

before_install:
  - openssl aes-256-cbc -pass pass:$PGP_KEY_PASSWORD -in ./.ci/secring.gpg.enc -out ~/secring.gpg -d -md md5
  - chmod a+x gradlew
  - chmod a+x ./.ci/prepare-travis.sh
  - . ./.ci/prepare-travis.sh

install: true

script:
  - . ./.ci/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CROPDB_VERSION=4.0.1-SNAPSHOT
    - PGP_KEY_FILE=~/secring.gpg